apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  containers:
    - name: nginx
      image: bitnami/nginx:1.21.6
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP
      env:
        - name: BITNAMI_DEBUG
          value: 'false'
      resources:
        limits:
          cpu: 100m
          memory: 300Mi
        requests:
          cpu: 10m
          memory: 50Mi
      livenessProbe:
        tcpSocket:
          port: http
        timeoutSeconds: 5
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 6
      readinessProbe:
        tcpSocket:
          port: http
        initialDelaySeconds: 5
        timeoutSeconds: 3
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 3
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
      securityContext:
        capabilities:
          drop:
            - all
        privileged: false
        runAsUser: 1001
        runAsNonRoot: true
        readOnlyRootFilesystem: false
        allowPrivilegeEscalation: false
  restartPolicy: Always
  terminationGracePeriodSeconds: 10
  
